# NOTE: update this with your service name
service: sundaycandy-serverless

# Create an optimized package for our functions
package:
  excludeDevDependencies: false
  include:
    - node_modules/**

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2

functions:
  kakaoSignUp:
    handler: src/auth/kakaoSignUp.main
    events:
      - http:
          path: kakaoSignUp
          method: post
  preSignUp:
    handler: src/auth/preSignUp.main
    events:
      - http:
          path: preSignUp
          method: post
  preKakaoAuthentication:
    handler: src/auth/preKakaoAuthentication.main
    events:
      - http:
          path: preKakaoAuthentication
          method: post
custom:
  bundle:
    linting: false # Enable linting as a part of the build process
    tsConfig: "tsconfig.json" # Path to your 'tsconfig.json', if it's not in the root
    aliases: # Create an alias to 'import' modules easily with a custom path
      - src: src
    packager: yarn
#   stage: dev
#   appSync:
#     name: ${self:service}-${self:custom.stage}
#     authenticationType: AMAZON_COGNITO_USER_POOLS
#     schema: schema.grapqhl
#   userPoolConfig:
#     awsRegion: ap-northeast-2
#     defaultAction: ALLOW
#     userPoolId: 68heoqrl708fhl8666ku89it90
